#!/bin/bash

echo "Creating .env file for Binder..."

cat <<EOF > .env
HUGGINGFACEHUB_API_TOKEN=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
TELEGRAM_BOT_TOKEN=7361673542:AAE3Lnxsv6F4d8_h6F76s_KgzNqQeQi03no
TELEGRAM_CHAT_ID=1003347918

EOF

echo ".env file created."
