name: chatbot_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - panel
  - param
  - pip
  - pip:
      - langchain
      - sentence-transformers
      - transformers
      - python-dotenv
